version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: compose/local/Dockerfile
    ports:
      - "8000:8000"
    restart: on-failure
    env_file: example.env
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000